version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - /home/k8master/stellar:/app/logs:ro
    environment:
      - LOG_PATH=/app/logs/cli_logs.jsonl

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
