services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ${SCI_LOG_DIR}:/app/logs:ro
    environment:
      - LOG_PATH=/app/logs/cli_logs.jsonl

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    ports:
      - "5173:5173"
    depends_on:
      - backend

